{
 "title": "Router",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "router", "label": "Router", "query": { "query": "label_values(router)" } }
  ]
 },
 "panels": [
  { "title": "Tunnels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of outbound tunnels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "outbound_tunnel_count{router=\"$router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of transit tunnels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "transit_tunnels_count{router=\"$router\"}",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "Tunnel build success rate",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tunnel_build_success_count{router=\"$router\"}) / (sum(tunnel_build_success_count{router=\"$router\"}) + (sum(tunnel_build_failure_count{router=\"$router\"}) or vector(0))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnel test success rate",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tunnel_test_success_count{router=\"$router\"}) / (sum(tunnel_test_success_count{router=\"$router\"}) + sum(tunnel_test_failure_count{router=\"$router\"} or vector(0))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of inbound tunnels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "inbound_tunnel_count{router=\"$router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending tunnels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pending_inbound_tunnel_count{router=\"$router\"} +  pending_outbound_tunnel_count{router=\"$router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of tunnel messages received",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(tunnel_message_count{router=\"$router\"}[$__rate_interval])",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "Tunnel test success/failure",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(tunnel_test_success_count{router=\"$router\"}[$__interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(tunnel_test_failure_count{router=\"$router\"}[$__interval])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Tunnel test durations",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "tunnel_test_durations_bucket_bucket{router=\"$router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnel message fragment counts",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "tunnel_num_fragments_bucket{router=\"$router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  }
 ]
}